-- DEPARTMENT 테이블 생성 
CREATE TABLE DEPARTMENT (
    DEPNO NUMBER NOT NULL,
    DEPNAME CHAR(10),
    FLOOR NUMBER,
    PRIMARY KEY(DEPNO)
);

-- 데이터 삽입
INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);


-- EMPLOYEE 테이블 생성 
CREATE TABLE EMPLOYEE(
    EMPNO NUMBER NOT NULL,
    EMPNAME CHAR(10) UNIQUE,
    TITLE CHAR(10) DEFAULT '사원',
    MANAGER NUMBER,
    SALARY NUMBER CHECK(SALARY < 6000000),
    DNO NUMBER DEFAULT 1 CHECK(DNO IN (1,2,3,4)),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
    FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPNO) ON DELETE CASCADE
);

-- 데이터 삽입
INSERT INTO EMPLOYEE VALUES(4377, '이성래', '사장', NULL, 5000000, 2);
INSERT INTO EMPLOYEE VALUES(3426, '박영권', '과장', 4377, 3000000, 1);
INSERT INTO EMPLOYEE VALUES(3011, '이수민', '부장', 4377, 4000000, 3);
INSERT INTO EMPLOYEE VALUES(3427, '최종철', '사원', 3011, 1500000, 3);
INSERT INTO EMPLOYEE VALUES(1003, '조민희', '과장', 4377, 3000000, 2);
INSERT INTO EMPLOYEE VALUES(2106, '김창섭', '대리', 1003, 2500000, 2);
INSERT INTO EMPLOYEE VALUES(1365, '김상원', '사원', 3426, 1500000, 1);

-- EMP_PLANNING 뷰 생성
CREATE VIEW EMP_PLANNING
AS 
SELECT E.EMPNAME, E.TITLE, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO=D.DEPNO AND D.DEPNAME='기획';

-- 테이블 & 뷰 목록 확인
SELECT * FROM tab;

-- 테이블 구조 
DESC DEPARTMENT;
DESC EMPLOYEE;

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

-- PROJECT 테이블 생성 
CREATE TABLE PROJECT (
    Projno NUMBER NOT NULL,
    Projname CHAR(15) NOT NULL,
    Budget NUMBER
);

-- PROJECT 테이블 변경 (컬럼 추가/삭제) 
ALTER TABLE PROJECT ADD Manager NUMBER;
ALTER TABLE PROJECT DROP COLUMN Manager;





