CREATE TABLE DEPARTMENT (
    DEPTNO NUMBER NOT NULL,
    DEPTNAME CHAR(10),
    FLOOR NUMBER,
    PRIMARY KEY(DEPTNO)
);

CREATE TABLE EMPLOYEE (
    EMPNO NUMBER NOT NULL,
    EMPNAME CHAR(10) UNIQUE,
    TITLE CHAR(10),
    MANAGER NUMBER,
    SALARY NUMBER,
    HIREDATE DATE,
    DNO NUMBER,
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
    FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPNO)
);

INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);

INSERT INTO EMPLOYEE VALUES(4377, '이성래', '사장', NULL, 5000000, '1996-01-05', 2);
INSERT INTO EMPLOYEE VALUES(1234, '장건호', '부장', 4377, 4200000, '1996-11-23', 1);
INSERT INTO EMPLOYEE VALUES(3426, '박영권', '과장', 1234, 3000000, '1998-07-20', 1);
INSERT INTO EMPLOYEE VALUES(1365, '김상원', '사원', 3426, 1500000, '2004-02-26', 1);
INSERT INTO EMPLOYEE VALUES(1099, '이재원', '사원', 3426, 1800000, '2003-12-21', 1);
INSERT INTO EMPLOYEE VALUES(3011, '이수민', '부장', 4377, 4300000, '1996-04-30', 3);
INSERT INTO EMPLOYEE VALUES(2468, '조범수', '과장', 3011, 3500000, '1998-12-17', 3);
INSERT INTO EMPLOYEE VALUES(2544, '오준석', '대리', 2468, 2700000, '2002-08-25', 3);
INSERT INTO EMPLOYEE VALUES(1003, '조민희', '대리', 2468, 2600000, '2001-02-19', 2);
INSERT INTO EMPLOYEE VALUES(3427, '최종철', '사원', 1003, 1500000, '2005-10-28', 3);
INSERT INTO EMPLOYEE VALUES(3228, '김주훈', '부장', 4377, 4000000, '1997-03-06', 2);
INSERT INTO EMPLOYEE VALUES(2106, '김창섭', '대리', 3228, 2500000, '2003-03-05', 2);


SELECT DEPNAME, DEPNO FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT TITLE FROM EMPLOYEE;
SELECT DISTINCT TITLE FROM EMPLOYEE;
SELECT EMPNAME, TITLE FROM EMPLOYEE
WHERE DNO = 3;

SELECT EMPNAME FROM EMPLOYEE
WHERE TITLE='과장';

SELECT EMPNAME, HIREDATE FROM EMPLOYEE
WHERE HIREDATE >= '2000-2-1';

SELECT EMPNAME, TITLE FROM EMPLOYEE 
WHERE NOT TITLE = '과장';
SELECT EMPNAME, TITLE FROM EMPLOYEE 
WHERE TITLE <> '과장';

SELECT EMPNAME, TITLE, SALARY FROM EMPLOYEE 
WHERE DNO = 2 AND SALARY > 2500000;

SELECT EMPNAME, TITLE, SALARY FROM EMPLOYEE 
WHERE SALARY >= 2000000 AND SALARY <=3000000;

SELECT EMPNAME, TITLE, SALARY FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 3000000;

SELECT EMPNAME, TITLE, SALARY FROM EMPLOYEE
WHERE SALARY > 3000000 AND TITLE <> '과장';

SELECT EMPNAME, TITLE, DNO FROM EMPLOYEE
WHERE TITLE = '대리'
OR TITLE = '과장' 
OR TITLE = '부장';

SELECT EMPNAME, TITLE, DNO FROM EMPLOYEE
WHERE TITLE IN ('대리', '과장', '부장');

SELECT EMPNAME, TITLE, DNO FROM EMPLOYEE
WHERE TITLE IN ('대리', '과장') AND DNO = 2;

SELECT EMPNAME, TITLE FROM EMPLOYEE
WHERE EMPNAME LIKE '김%';

SELECT EMPNAME, TITLE FROM EMPLOYEE
WHERE MANAGER IS NULL;

SELECT SALARY, EMPNAME FROM EMPLOYEE
ORDER BY SALARY;

SELECT SALARY, EMPNAME FROM EMPLOYEE 
ORDER BY SALARY DESC;

SELECT SALARY, EMPNAME FROM EMPLOYEE 
ORDER BY DNO, SALARY DESC;

SELECT COUNT(*) AS COUNT_EMP, AVG(SALARY) AS AVG_SAL FROM EMPLOYEE
WHERE DNO = 3;

SELECT E.EMPNAME, D.FLOOR 
FROM EMPLOYEE E, DEPARTMENT D 
WHERE E.DNO = D.DEPNO;

SELECT E.EMPNAME, E.TITLE 
FROM EMPLOYEE E, DEPARTMENT D 
WHERE E.DNO = D.DEPNO 
    AND D.DEPNAME = '개발';
    
SELECT EMPNAME, FLOOR 
FROM EMPLOYEE INNER JOIN DEPARTMENT 
    ON EMPLOYEE.DNO = DEPARTMENT.DEPNO;
    
SELECT EMPNAME, TITLE 
FROM EMPLOYEE
WHERE DNO = 
    (SELECT DNO 
     FROM EMPLOYEE
     WHERE EMPNAME = '김상원');
     
SELECT EMPNAME 
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

SELECT EMPNAME 
FROM EMPLOYEE 
WHERE DNO IN 
    (SELECT DEPNO 
     FROM DEPARTMENT 
     WHERE FLOOR = 8 OR FLOOR = 9);
     
SELECT DEPNO, DEPNAME, FLOOR 
FROM DEPARTMENT D 
WHERE NOT EXISTS 
    (SELECT * FROM EMPLOYEE E 
     WHERE E.DNO = D.DEPNO);
     
SELECT EMPNAME, TITLE, DNO 
FROM EMPLOYEE AS E1 
WHERE EXISTS 
    (SELECT * FROM EMPLOYEE AS E2
     WHERE E2.EMPNAME = '조민희'
     AND E1.TITLE = E2.TITLE 
     AND E1.DNO = E2.DNO);
     
     
SELECT EMPNAME, TITLE, DNO 
FROM EMPLOYEE
WHERE (TITLE, DNO) = 
        (SELECT TITLE, DNO 
         FROM EMPLOYEE
         WHERE EMPNAME = '조민희');
         
SELECT DEPNAME, AVG(SALARY) 
FROM EMPLOYEE E, DEPARTMENT D 
WHERE E.DNO = D.DEPNO 
GROUP BY DEPNAME;

SELECT DEPNAME, AVG(SALARY) AS AVERAGE_SAL 
FROM EMPLOYEE E, DEPARTMENT D 
WHERE E.DNO = D.DEPNO 
GROUP BY DEPNAME;

SELECT DEPNAME, SUM(SALARY)
FROM EMPLOYEE E, DEPARTMENT D 
WHERE E.DNO = D.DEPNO 
GROUP BY DEPNAME 
HAVING SUM(SALARY) BETWEEN 1000000 AND 1500000;

SELECT DEPNAME, SUM(SALARY) 
FROM EMPLOYEE  E, DEPARTMENT  D 
WHERE E.DNO = D.DEPNO 
GROUP BY DEPNAME 
HAVING SUM(SALARY) BETWEEN 1100000 AND 1400000;


