-- 모든 사용자 보기
SELECT * FROM all_users;

-- 새로운 사용자 추가
CREATE USER purple IDENTIFIED BY "java$!";

-- 사용자에게 권한 부여
GRANT CONNECT, RESOURCE TO purple;
GRANT CREATE SESSION, CREATE VIEW TO purple;

-- 기본 테이블스페이스 지정 
ALTER USER purple DEFAULT TABLESPACE USERS;
ALTER USER purple TEMPORARY TABLESPACE TEMP;
ALTER USER purple DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


